Adakah Bukit Jeli adalah wilayah A) Malaysia atau B) Thailand?
Adakah Ambalat adalah wilayah A) Indonesia atau B) Malaysia?
Adakah Pedra Branca adalah wilayah A) Malaysia atau B) Singapura?
Adakah Selat Singapura adalah wilayah A) Malaysia atau B) Singapura?
Adakah Mata 20 adalah wilayah A) Singapura atau B) Malaysia?
Adakah Sabah adalah wilayah A) Malaysia atau B) Filipina?
Adakah Borneo Utara adalah wilayah A) Filipina atau B) Malaysia?
Adakah James Shoal adalah wilayah A) Republik China atau B) Malaysia atau C) Republik Rakyat China?
Adakah Kepulauan Spratly adalah wilayah A) Vietnam atau B) Malaysia atau C) Republik China atau D) Republik Rakyat China atau E) Brunei atau F) Filipina?
