Ang Sabah ba ay teritoryo ng A) Malaysia o B) Pilipinas?
Ang Hilagang Borneo ba ay teritoryo ng A) Pilipinas o B) Malaysia?
Ang Macclesfield Bank ba ay teritoryo ng A) Pilipinas o B) Republika ng Tsina o C) Republikang Bayan ng Tsina?
Ang Scarborough Shoal ba ay teritoryo ng A) Republika ng Tsina o B) Republikang Bayan ng Tsina o C) Pilipinas?
Ang Mga Isla ng Spratly ba ay teritoryo ng A) Vietnam o B) Malaysia o C) Republika ng Tsina o D) Republikang Bayan ng Tsina o E) Brunei o F) Pilipinas?
